export const AGREGAR_CONTACTO = "AGREGAR_CONTACTO";
export const ELIMINAR_CONTACTO = "ELIMINAR_CONTACTO";
export const OBTENER_CONTACTO = "OBTENER_CONTACTO";
export const EDITAR_CONTACTO = "EDITAR_CONTACTO";

export const FILTRO_CONTRACTOS = "FILTRO_CONTRACTOS";
export const OBTENER_FILTRO = "OBTENER_FILTRO";

export const MOSTRAR_MODAL = "MOSTRAR_MODAL";
export const OCULTAR_MODAL = "OCULTAR_MODAL";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA"
export const OCULTAR_ALERTA = "OCULTAR_ALERTA"
